// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"


///////////////////// SCREENS ////////////////////

#include "screens/ui_screen1.h"
#include "screens/ui_Screen2.h"
#include "screens/ui_Screen3.h"
#include "screens/ui_Screen4.h"

///////////////////// VARIABLES ////////////////////


// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_radaricon_png);    // assets/radaricon.png
LV_IMG_DECLARE(ui_img_safe_png);    // assets/safe.png
LV_IMG_DECLARE(ui_img_posture1_png);    // assets/posture1.png
LV_IMG_DECLARE(ui_img_fall_png);    // assets/fall.png
LV_IMG_DECLARE(ui_img_posture2_png);    // assets/posture2.png
LV_IMG_DECLARE(ui_img_posture3_png);    // assets/posture3.png
LV_IMG_DECLARE(ui_img_posture4_png);    // assets/posture4.png
LV_IMG_DECLARE(ui_img_posture5_png);    // assets/posture5.png

// UI INIT
void ui_init(void);
void ui_destroy(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
