// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#include <stdbool.h>
#include "../app/radar_sensor.h"

#ifdef __cplusplus
extern "C" {
#endif


void ui_navigation_init(void);
void ui_screen_gesture_handler(lv_event_t * e);
void slider_height_value_cb(lv_event_t * e);
void slider_range_value_cb(lv_event_t * e);
void slider_sensitivity_value_cb(lv_event_t * e);
void switch_alert_value_cb(lv_event_t * e);
void switch_state_value_cb(lv_event_t * e);
void slider_volume_value_cb(lv_event_t * e);
void button_reset_value_cb(lv_event_t * e);

void load_progressbar_and_playaudio(void);
void ui_screen3_set_fall_detected(bool human_present, bool fall_detected);
void ui_screen3_set_posture(human_posture_t posture);
void ui_screen3_start_monitor(void);
void ui_screen4_update_sensor_log(void);
void ui_screen4_update_client_ip();

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
