/**
 * @file ui_Screen3.h
 * @brief Radar Human Detection & Fall Monitor
 * @details ESP32-S3-BOX-3 based real-time human presence detection and fall
 *          monitoring system using LD6001 mmWave radar sensor.
 * @author PratyushGehlot
 * @see https://github.com/PratyushGehlot/radar_human_detectmon
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#ifndef UI_SCREEN3_H
#define UI_SCREEN3_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_Screen3
extern void ui_Screen3_screen_init(void);
extern void ui_Screen3_screen_destroy(void);
extern lv_obj_t * ui_Screen3;
extern lv_obj_t * ui_Label31;
extern lv_obj_t * ui_Label33;
extern lv_obj_t * ui_ImageSafe;
extern lv_obj_t * ui_imgsitting;
extern lv_obj_t * ui_imgfalldetected;
extern lv_obj_t * ui_imgdownsit;
extern lv_obj_t * ui_imgstanding;
extern lv_obj_t * ui_imglying;
extern lv_obj_t * ui_imgfall;
extern lv_obj_t * ui_Label32;
extern lv_obj_t * ui_Label34;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

