// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_screen1 = NULL;
lv_obj_t * ui_Bar1 = NULL;
lv_obj_t * ui_TextArea1 = NULL;
lv_obj_t * ui_Image13 = NULL;
lv_obj_t * ui_Label27 = NULL;
// event funtions
void ui_event_screen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_GESTURE &&  lv_indev_get_gesture_dir(lv_indev_get_act()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_get_act());
        ui_screen_gesture_handler(e);
    }
}

void ui_event_Image13(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_Screen3, LV_SCR_LOAD_ANIM_FADE_ON, 500, 0, &ui_Screen3_screen_init);
    }
}

// build funtions

void ui_screen1_screen_init(void)
{
    ui_screen1 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_screen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_screen1, lv_color_hex(0x618E83), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_screen1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Bar1 = lv_bar_create(ui_screen1);
    lv_bar_set_mode(ui_Bar1, LV_BAR_MODE_SYMMETRICAL);
    lv_bar_set_value(ui_Bar1, 25, LV_ANIM_OFF);
    lv_bar_set_start_value(ui_Bar1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Bar1, 150);
    lv_obj_set_height(ui_Bar1, 10);
    lv_obj_set_x(ui_Bar1, -3);
    lv_obj_set_y(ui_Bar1, 78);
    lv_obj_set_align(ui_Bar1, LV_ALIGN_CENTER);

    lv_obj_set_style_bg_color(ui_Bar1, lv_color_hex(0x0C5B97), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Bar1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    ui_TextArea1 = lv_textarea_create(ui_screen1);
    lv_obj_set_width(ui_TextArea1, 234);
    lv_obj_set_height(ui_TextArea1, LV_SIZE_CONTENT);    /// 53
    lv_obj_set_x(ui_TextArea1, -2);
    lv_obj_set_y(ui_TextArea1, -78);
    lv_obj_set_align(ui_TextArea1, LV_ALIGN_CENTER);
    lv_textarea_set_text(ui_TextArea1, "Privacy Safe Radar based Home Safety Monitoring");
    lv_textarea_set_placeholder_text(ui_TextArea1, "Placeholder...");
    lv_obj_set_style_text_color(ui_TextArea1, lv_color_hex(0x127B85), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_TextArea1, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_TextArea1, &lv_font_montserrat_14, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_TextArea1, lv_color_hex(0xC6139D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_TextArea1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Image13 = lv_img_create(ui_screen1);
    lv_img_set_src(ui_Image13, &ui_img_radaricon_png);
    lv_obj_set_width(ui_Image13, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_Image13, LV_SIZE_CONTENT);    /// 100
    lv_obj_set_x(ui_Image13, -3);
    lv_obj_set_y(ui_Image13, 10);
    lv_obj_set_align(ui_Image13, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Image13, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_Image13, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label27 = lv_label_create(ui_screen1);
    lv_obj_set_width(ui_Label27, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label27, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label27, -2);
    lv_obj_set_y(ui_Label27, 104);
    lv_obj_set_align(ui_Label27, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label27, "[No camera Just Radar]");
    lv_obj_set_style_text_color(ui_Label27, lv_color_hex(0xFBFB15), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label27, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Image13, ui_event_Image13, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_screen1, ui_event_screen1, LV_EVENT_ALL, NULL);

}

void ui_screen1_screen_destroy(void)
{
    if(ui_screen1) lv_obj_del(ui_screen1);

    // NULL screen variables
    ui_screen1 = NULL;
    ui_Bar1 = NULL;
    ui_TextArea1 = NULL;
    ui_Image13 = NULL;
    ui_Label27 = NULL;

}
