// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen4 = NULL;
lv_obj_t * ui_Label41 = NULL;
lv_obj_t * ui_Label42 = NULL;
lv_obj_t * ui_TextArea9 = NULL;
lv_obj_t * ui_Label43 = NULL;
lv_obj_t * ui_Slider4 = NULL;
lv_obj_t * ui_Button2 = NULL;
lv_obj_t * ui_Label44 = NULL;
lv_obj_t * ui_Label45 = NULL;
lv_obj_t * ui_Label46 = NULL;
lv_obj_t * ui_Label24 = NULL;
lv_obj_t * ui_Label25 = NULL;
lv_obj_t * ui_Label26 = NULL;
lv_obj_t * ui_Dropdown2 = NULL;
// event funtions
void ui_event_Slider4(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_volume_value_cb(e);
    }
}

void ui_event_Button2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        button_reset_value_cb(e);
    }
}

// build funtions

void ui_Screen4_screen_init(void)
{
    ui_Screen4 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label41 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label41, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label41, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label41, -6);
    lv_obj_set_y(ui_Label41, -109);
    lv_obj_set_align(ui_Label41, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label41, "Advance Settings");

    ui_Label42 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label42, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label42, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label42, -109);
    lv_obj_set_y(ui_Label42, -91);
    lv_obj_set_align(ui_Label42, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label42, "Sensor Log:");

    ui_TextArea9 = lv_textarea_create(ui_Screen4);
    lv_obj_set_width(ui_TextArea9, 301);
    lv_obj_set_height(ui_TextArea9, 58);
    lv_obj_set_x(ui_TextArea9, -2);
    lv_obj_set_y(ui_TextArea9, -50);
    lv_obj_set_align(ui_TextArea9, LV_ALIGN_CENTER);
    lv_textarea_set_placeholder_text(ui_TextArea9, "Placeholder...");

    ui_Label43 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label43, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label43, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label43, -102);
    lv_obj_set_y(ui_Label43, -4);
    lv_obj_set_align(ui_Label43, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label43, "Audio Volume");

    ui_Slider4 = lv_slider_create(ui_Screen4);
    lv_slider_set_range(ui_Slider4, 0, 5);
    lv_slider_set_value(ui_Slider4, 3, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider4) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider4, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider4, 135);
    lv_obj_set_height(ui_Slider4, 10);
    lv_obj_set_x(ui_Slider4, 30);
    lv_obj_set_y(ui_Slider4, -4);
    lv_obj_set_align(ui_Slider4, LV_ALIGN_CENTER);

    ui_Button2 = lv_btn_create(ui_Screen4);
    lv_obj_set_width(ui_Button2, 124);
    lv_obj_set_height(ui_Button2, 29);
    lv_obj_set_x(ui_Button2, -88);
    lv_obj_set_y(ui_Button2, 95);
    lv_obj_set_align(ui_Button2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_Button2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label44 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label44, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label44, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label44, -89);
    lv_obj_set_y(ui_Label44, 95);
    lv_obj_set_align(ui_Label44, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label44, "Reset Sensor");

    ui_Label45 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label45, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label45, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label45, 132);
    lv_obj_set_y(ui_Label45, -3);
    lv_obj_set_align(ui_Label45, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label45, "60%");
    lv_obj_set_style_text_color(ui_Label45, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label45, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label46 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label46, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label46, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label46, 89);
    lv_obj_set_y(ui_Label46, 96);
    lv_obj_set_align(ui_Label46, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label46, "Auther:\nPratyush Gehlot");
    lv_obj_set_style_text_color(ui_Label46, lv_color_hex(0x793C59), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label46, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label24 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label24, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label24, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label24, -80);
    lv_obj_set_y(ui_Label24, 23);
    lv_obj_set_align(ui_Label24, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label24, "WiFi Client Address:");

    ui_Label25 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label25, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label25, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label25, 75);
    lv_obj_set_y(ui_Label25, 23);
    lv_obj_set_align(ui_Label25, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label25, "No client connected");
    lv_obj_set_style_text_color(ui_Label25, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label25, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label26 = lv_label_create(ui_Screen4);
    lv_obj_set_width(ui_Label26, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label26, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label26, -84);
    lv_obj_set_y(ui_Label26, 54);
    lv_obj_set_align(ui_Label26, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label26, "Sensor Calibration:");

    ui_Dropdown2 = lv_dropdown_create(ui_Screen4);
    lv_dropdown_set_options(ui_Dropdown2, "PRESET VALUES\nMANUAL\nAUTOMATIC");
    lv_obj_set_width(ui_Dropdown2, 157);
    lv_obj_set_height(ui_Dropdown2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown2, 71);
    lv_obj_set_y(ui_Dropdown2, 53);
    lv_obj_set_align(ui_Dropdown2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_add_event_cb(ui_Slider4, ui_event_Slider4, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Button2, ui_event_Button2, LV_EVENT_ALL, NULL);

}

void ui_Screen4_screen_destroy(void)
{
    if(ui_Screen4) lv_obj_del(ui_Screen4);

    // NULL screen variables
    ui_Screen4 = NULL;
    ui_Label41 = NULL;
    ui_Label42 = NULL;
    ui_TextArea9 = NULL;
    ui_Label43 = NULL;
    ui_Slider4 = NULL;
    ui_Button2 = NULL;
    ui_Label44 = NULL;
    ui_Label45 = NULL;
    ui_Label46 = NULL;
    ui_Label24 = NULL;
    ui_Label25 = NULL;
    ui_Label26 = NULL;
    ui_Dropdown2 = NULL;

}
