/**
 * @file ui_Screen3.c
 * @brief Radar Human Detection & Fall Monitor
 * @details ESP32-S3-BOX-3 based real-time human presence detection and fall
 *          monitoring system using LD6001 mmWave radar sensor.
 * @author PratyushGehlot
 * @see https://github.com/PratyushGehlot/radar_human_detectmon
 */

// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen3 = NULL;
lv_obj_t * ui_Label31 = NULL;
lv_obj_t * ui_Label33 = NULL;
lv_obj_t * ui_ImageSafe = NULL;
lv_obj_t * ui_imgsitting = NULL;
lv_obj_t * ui_imgfalldetected = NULL;
lv_obj_t * ui_imgdownsit = NULL;
lv_obj_t * ui_imgstanding = NULL;
lv_obj_t * ui_imglying = NULL;
lv_obj_t * ui_imgfall = NULL;
lv_obj_t * ui_Label32 = NULL;
lv_obj_t * ui_Label34 = NULL;
// event funtions

// build funtions

void ui_Screen3_screen_init(void)
{
    ui_Screen3 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label31 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label31, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label31, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label31, -107);
    lv_obj_set_y(ui_Label31, -88);
    lv_obj_set_align(ui_Label31, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label31, "Detection:");

    ui_Label33 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label33, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label33, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label33, -113);
    lv_obj_set_y(ui_Label33, 19);
    lv_obj_set_align(ui_Label33, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label33, "Posture:");

    ui_ImageSafe = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_ImageSafe, &ui_img_safe_png);
    lv_obj_set_width(ui_ImageSafe, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_ImageSafe, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_ImageSafe, 82);
    lv_obj_set_y(ui_ImageSafe, -53);
    lv_obj_set_align(ui_ImageSafe, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_ImageSafe, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_ImageSafe, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgsitting = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_imgsitting, &ui_img_posture1_png);
    lv_obj_set_width(ui_imgsitting, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imgsitting, LV_SIZE_CONTENT);    /// 102
    lv_obj_set_x(ui_imgsitting, 74);
    lv_obj_set_y(ui_imgsitting, 58);
    lv_obj_set_align(ui_imgsitting, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgsitting, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgsitting, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgfalldetected = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_imgfalldetected, &ui_img_fall_png);
    lv_obj_set_width(ui_imgfalldetected, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imgfalldetected, LV_SIZE_CONTENT);    /// 104
    lv_obj_set_x(ui_imgfalldetected, 88);
    lv_obj_set_y(ui_imgfalldetected, -52);
    lv_obj_set_align(ui_imgfalldetected, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgfalldetected, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgfalldetected, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgdownsit = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_imgdownsit, &ui_img_posture2_png);
    lv_obj_set_width(ui_imgdownsit, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imgdownsit, LV_SIZE_CONTENT);    /// 92
    lv_obj_set_x(ui_imgdownsit, 76);
    lv_obj_set_y(ui_imgdownsit, 54);
    lv_obj_set_align(ui_imgdownsit, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgdownsit, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgdownsit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgstanding = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_imgstanding, &ui_img_posture3_png);
    lv_obj_set_width(ui_imgstanding, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imgstanding, LV_SIZE_CONTENT);    /// 119
    lv_obj_set_x(ui_imgstanding, 81);
    lv_obj_set_y(ui_imgstanding, 45);
    lv_obj_set_align(ui_imgstanding, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgstanding, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgstanding, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imglying = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_imglying, &ui_img_posture4_png);
    lv_obj_set_width(ui_imglying, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imglying, LV_SIZE_CONTENT);    /// 77
    lv_obj_set_x(ui_imglying, 82);
    lv_obj_set_y(ui_imglying, 61);
    lv_obj_set_align(ui_imglying, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imglying, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imglying, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_imgfall = lv_img_create(ui_Screen3);
    lv_img_set_src(ui_imgfall, &ui_img_posture5_png);
    lv_obj_set_width(ui_imgfall, LV_SIZE_CONTENT);   /// 100
    lv_obj_set_height(ui_imgfall, LV_SIZE_CONTENT);    /// 106
    lv_obj_set_x(ui_imgfall, 88);
    lv_obj_set_y(ui_imgfall, 52);
    lv_obj_set_align(ui_imgfall, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_imgfall, LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_clear_flag(ui_imgfall, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Label32 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label32, LV_SIZE_CONTENT);   /// 352
    lv_obj_set_height(ui_Label32, LV_SIZE_CONTENT);    /// 2
    lv_obj_set_x(ui_Label32, -79);
    lv_obj_set_y(ui_Label32, -54);
    lv_obj_set_align(ui_Label32, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label32, "Human Detected");
    lv_obj_set_style_text_color(ui_Label32, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label32, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label34 = lv_label_create(ui_Screen3);
    lv_obj_set_width(ui_Label34, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label34, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label34, -106);
    lv_obj_set_y(ui_Label34, 60);
    lv_obj_set_align(ui_Label34, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label34, "Standing \nMoving");
    lv_obj_set_style_text_color(ui_Label34, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label34, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

}

void ui_Screen3_screen_destroy(void)
{
    if(ui_Screen3) lv_obj_del(ui_Screen3);

    // NULL screen variables
    ui_Screen3 = NULL;
    ui_Label31 = NULL;
    ui_Label33 = NULL;
    ui_ImageSafe = NULL;
    ui_imgsitting = NULL;
    ui_imgfalldetected = NULL;
    ui_imgdownsit = NULL;
    ui_imgstanding = NULL;
    ui_imglying = NULL;
    ui_imgfall = NULL;
    ui_Label32 = NULL;
    ui_Label34 = NULL;

}
