// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"

lv_obj_t * ui_Screen2 = NULL;
lv_obj_t * ui_Dropdown1 = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_Label2 = NULL;
lv_obj_t * ui_Label3 = NULL;
lv_obj_t * ui_Label4 = NULL;
lv_obj_t * ui_Label5 = NULL;
lv_obj_t * ui_Label6 = NULL;
lv_obj_t * ui_Slider1 = NULL;
lv_obj_t * ui_Slider2 = NULL;
lv_obj_t * ui_Slider3 = NULL;
lv_obj_t * ui_Switch1 = NULL;
lv_obj_t * ui_Switch2 = NULL;
lv_obj_t * ui_Label7 = NULL;
lv_obj_t * ui_Label8 = NULL;
lv_obj_t * ui_Label9 = NULL;
lv_obj_t * ui_Labelstate = NULL;
lv_obj_t * ui_Label10 = NULL;
// event funtions
void ui_event_Dropdown1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) 
    {
        //dropdown_mode_value_cb(e);
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_height_value_cb(e);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_range_value_cb(e);
    }
}

void ui_event_Slider3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        slider_sensitivity_value_cb(e);
    }
}

void ui_event_Switch1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_alert_value_cb(e);
    }
}

void ui_event_Switch2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        switch_state_value_cb(e);
    }
}

// build funtions

void ui_Screen2_screen_init(void)
{
    ui_Screen2 = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_Screen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_Dropdown1 = lv_dropdown_create(ui_Screen2);
    lv_dropdown_set_options(ui_Dropdown1, "Bathroom Fall detection\nElderly monitoring\nPresense detection");
    lv_obj_set_width(ui_Dropdown1, 247);
    lv_obj_set_height(ui_Dropdown1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Dropdown1, 25);
    lv_obj_set_y(ui_Dropdown1, -61);
    lv_obj_set_align(ui_Dropdown1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_Dropdown1, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags

    ui_Label1 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -128);
    lv_obj_set_y(ui_Label1, -60);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Mode");

    ui_Label2 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label2, -102);
    lv_obj_set_y(ui_Label2, -100);
    lv_obj_set_align(ui_Label2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label2, "Device State");

    ui_Label3 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label3, -121);
    lv_obj_set_y(ui_Label3, -18);
    lv_obj_set_align(ui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label3, "Height");

    ui_Label4 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label4, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label4, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label4, -123);
    lv_obj_set_y(ui_Label4, 20);
    lv_obj_set_align(ui_Label4, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label4, "Range");

    ui_Label5 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label5, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label5, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label5, -113);
    lv_obj_set_y(ui_Label5, 97);
    lv_obj_set_align(ui_Label5, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label5, "Audio Alert");

    ui_Label6 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label6, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label6, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label6, -120);
    lv_obj_set_y(ui_Label6, 56);
    lv_obj_set_align(ui_Label6, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label6, "Sensitivity");

    ui_Slider1 = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_Slider1, 5, 10);
    lv_slider_set_value(ui_Slider1, 8, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 2, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_x(ui_Slider1, 4);
    lv_obj_set_y(ui_Slider1, -17);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);

    ui_Slider2 = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_Slider2, 1, 10);
    lv_slider_set_value(ui_Slider2, 5, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 5, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_x(ui_Slider2, 4);
    lv_obj_set_y(ui_Slider2, 18);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Slider2, LV_OBJ_FLAG_GESTURE_BUBBLE);      /// Flags

    ui_Slider3 = lv_slider_create(ui_Screen2);
    lv_slider_set_range(ui_Slider3, 0, 19);
    lv_slider_set_value(ui_Slider3, 3, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider3) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider3, 16, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider3, 149);
    lv_obj_set_height(ui_Slider3, 10);
    lv_obj_set_x(ui_Slider3, 4);
    lv_obj_set_y(ui_Slider3, 56);
    lv_obj_set_align(ui_Slider3, LV_ALIGN_CENTER);

    ui_Switch1 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch1, 50);
    lv_obj_set_height(ui_Switch1, 25);
    lv_obj_set_x(ui_Switch1, -33);
    lv_obj_set_y(ui_Switch1, 96);
    lv_obj_set_align(ui_Switch1, LV_ALIGN_CENTER);

    ui_Switch2 = lv_switch_create(ui_Screen2);
    lv_obj_set_width(ui_Switch2, 50);
    lv_obj_set_height(ui_Switch2, 25);
    lv_obj_set_x(ui_Switch2, -10);
    lv_obj_set_y(ui_Switch2, -102);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);

    ui_Label7 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label7, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label7, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label7, 114);
    lv_obj_set_y(ui_Label7, -17);
    lv_obj_set_align(ui_Label7, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label7, "3 m");
    lv_obj_set_style_text_color(ui_Label7, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label8 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label8, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label8, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label8, 115);
    lv_obj_set_y(ui_Label8, 16);
    lv_obj_set_align(ui_Label8, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label8, "6 m");
    lv_obj_set_style_text_color(ui_Label8, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label9 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label9, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label9, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label9, 108);
    lv_obj_set_y(ui_Label9, 55);
    lv_obj_set_align(ui_Label9, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label9, "2");
    lv_obj_set_style_text_color(ui_Label9, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Labelstate = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Labelstate, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Labelstate, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Labelstate, 102);
    lv_obj_set_y(ui_Labelstate, -100);
    lv_obj_set_align(ui_Labelstate, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Labelstate, "Stopped");
    lv_obj_set_style_text_color(ui_Labelstate, lv_color_hex(0x1A0C0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Labelstate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_radius(ui_Labelstate, 4, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_color(ui_Labelstate, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_opa(ui_Labelstate, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_width(ui_Labelstate, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_outline_pad(ui_Labelstate, 3, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label10 = lv_label_create(ui_Screen2);
    lv_obj_set_width(ui_Label10, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label10, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label10, 34);
    lv_obj_set_y(ui_Label10, 95);
    lv_obj_set_align(ui_Label10, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label10, "OFF");
    lv_obj_set_style_text_color(ui_Label10, lv_color_hex(0xFF00AB), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Dropdown1, ui_event_Dropdown1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider3, ui_event_Slider3, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch1, ui_event_Switch1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Switch2, ui_event_Switch2, LV_EVENT_ALL, NULL);

}

void ui_Screen2_screen_destroy(void)
{
    if(ui_Screen2) lv_obj_del(ui_Screen2);

    // NULL screen variables
    ui_Screen2 = NULL;
    ui_Dropdown1 = NULL;
    ui_Label1 = NULL;
    ui_Label2 = NULL;
    ui_Label3 = NULL;
    ui_Label4 = NULL;
    ui_Label5 = NULL;
    ui_Label6 = NULL;
    ui_Slider1 = NULL;
    ui_Slider2 = NULL;
    ui_Slider3 = NULL;
    ui_Switch1 = NULL;
    ui_Switch2 = NULL;
    ui_Label7 = NULL;
    ui_Label8 = NULL;
    ui_Label9 = NULL;
    ui_Labelstate = NULL;
    ui_Label10 = NULL;

}
